### ISSUE TITLE
Instructions for training hand models

### ISSUE THREAD

**Issue by jyunlee** [jianwang-mpi/egowholemocap#7]
Hello, thank you for the great work! 👏
Could you also provide the instructions for training hand estimation models?
Thanks for reading my question!

**Comment by jianwang-mpi** [comment]
Hello,

Sure, but I have been quite busy recently. I will try to first release the uncleaned code / simple instructions in a week.

**Comment by jianwang-mpi** [comment]
Added some config files and instructions to fine-tune hand models in Readme. 

Please check.

**Comment by jyunlee** [comment]
Thank you for the quick reply despite your busy schedule! 👍
However, it seems like `RenderpeopleMixamoHandTrainDataset` used in `configs/egofullbody/egohand/hands4whole_train_synthetic.py` is not defined in `mmpose/datasets/__init__.py`.
Could you also release the dataset implementation? Thanks again for your help in advance!

```
Traceback (most recent call last):
  File "/mnt/home/jihyunlee/workspace/egowholemocap/tools/train.py", line 201, in <module>
    main()
  File "/mnt/home/jihyunlee/workspace/egowholemocap/tools/train.py", line 176, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/mnt/home/jihyunlee/workspace/egowholemocap/mmpose/datasets/builder.py", line 90, in build_dataset                                                                                                      
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/mnt/home/jihyunlee/env/lib/python3.10/site-packages/mmcv_full-1.7.1-py3.10.egg/mmcv/utils/registry.py", line 61, in build_from_cfg      
    raise KeyError(
KeyError: 'RenderpeopleMixamoHandTrainDataset is not in the dataset registry'
```

**Comment by jianwang-mpi** [comment]
Updated the code.

Sorry for the error.

**Comment by jyunlee** [comment]
Thank you for the update! Now it works well! 👍
